[package]
name = "cbf"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.77"
bacon-sci = "0.14.0"
clap = { version = "4.4.12", features = ["derive"] }
serde = "1.0.193"
